CREATE TABLE [dbo].[Test4] (
    [RowNumber]        INT            IDENTITY (0, 1) NOT NULL,
    [EventClass]       INT            NULL,
    [ApplicationName]  NVARCHAR (128) NULL,
    [BinaryData]       IMAGE          NULL,
    [CPU]              INT            NULL,
    [ClientProcessID]  INT            NULL,
    [DatabaseID]       INT            NULL,
    [DatabaseName]     NVARCHAR (128) NULL,
    [Duration]         BIGINT         NULL,
    [EndTime]          DATETIME       NULL,
    [Error]            INT            NULL,
    [EventSequence]    BIGINT         NULL,
    [GroupID]          INT            NULL,
    [HostName]         NVARCHAR (128) NULL,
    [IntegerData]      INT            NULL,
    [IsSystem]         INT            NULL,
    [LoginName]        NVARCHAR (128) NULL,
    [LoginSid]         IMAGE          NULL,
    [NTDomainName]     NVARCHAR (128) NULL,
    [NTUserName]       NVARCHAR (128) NULL,
    [ObjectName]       NVARCHAR (128) NULL,
    [Reads]            BIGINT         NULL,
    [RequestID]        INT            NULL,
    [RowCounts]        BIGINT         NULL,
    [SPID]             INT            NULL,
    [ServerName]       NVARCHAR (128) NULL,
    [SessionLoginName] NVARCHAR (128) NULL,
    [StartTime]        DATETIME       NULL,
    [TextData]         NTEXT          NULL,
    [TransactionID]    BIGINT         NULL,
    [Writes]           BIGINT         NULL,
    [XactSequence]     BIGINT         NULL,
    [IntegerData2]     INT            NULL,
    [LineNumber]       INT            NULL,
    [NestLevel]        INT            NULL,
    [ObjectID]         INT            NULL,
    [ObjectType]       INT            NULL,
    [Offset]           INT            NULL,
    [SourceDatabaseID] INT            NULL,
    [EventSubClass]    INT            NULL,
    [IndexID]          INT            NULL,
    PRIMARY KEY CLUSTERED ([RowNumber] ASC)
);

